language: android
dist: trusty
android:
  components:
    # The BuildTools version used by your project
    - build-tools-29.0.1

    # The SDK version used to compile your project
    - android-29

before_script: 
    - chmod +x gradlew

script:
    - ./gradlew build
