version: "3.2"

services:
  demo:
    image: openvidu/openvidu-server-kms:latest
    ports:
      - "4443:4443"
    environment:
      openvidu.secret: "MY_SECRET"
      openvidu.publicurl: "https://192.168.56.148:4443"
      server.ssl.key-store: /run/secrets/openvidu.jks
      server.ssl.key-store-password: "password"
      server.ssl.key-alias: "key1"
    secrets:
      - openvidu.jks

secrets:
  openvidu.jks:
    file: openvidu.jks
